### ISSUE TITLE
Using this to restream a TikTok live into YouTube using ffmpeg

### ISSUE THREAD

**Issue by dersa7** [roju/tiktok-live-recorder#10]
So I am using this and it's working really well, no problems whatsoever and I've been able to automatically record all live videos of a specific user.
Now instead of downloading the live I want to stream it to YouTube using ffmpeg, I guess this program already gets the stream video link for the live so I can post it on my ffmpeg command and run it 24/7, if anyone can help me with this I will be very happy.
Thanks everyone.
Here is the ffmpeg command that is used to restream a video from a different website(I found it on a reddit): 
ffmpeg -multiple_requests 1 -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 2 -re -user_agent "Mozilla/5.0 etc" -referer "https://streaming-service.com/" -i https://other-website.net/6000/chunklist.m3u8/exp=####/idsandtokens" -c:v copy -c:a aac -ar 44100 -ab 128k -ac 2 -strict -2 -flags +global_header -bsf:a aac_adtstoasc -bufsize 3000k -f flv rtmp://my-rtmp-server:1234/stream-key

**Comment by dersa7** [comment]
> I don't think that's a good idea, and that's not what we're doing here. This is not a commercial project.

Hello again thanks for replying, I am not using it for a commercial purpose, it's just a way so I can make people access the content on YouTube and archive it( the content is educational and the streamer is an old guy who permitted me to archive his videos forthe  future

**Comment by dersa7** [comment]
Hello again I was able to create this using chat gpt to modify this code and it works flawlessly I was able to stream to YouTube with no lag on a cheap 1$ vps, I can provide the code if the author wants to include it into the project, thank you all

**Comment by fulopsoma23** [comment]
@dersa7 I'm very interested in this. Could you send me the code?
