### ISSUE TITLE
Recording just freezes

### ISSUE THREAD

**Issue by Sullyscharger** [roju/tiktok-live-recorder#16]
Hi, thanks for the fork but recently I've come across an issue when recording live streams. After starting the recording, it will record for a few minutes as I see the timer going but suddenly just stops as in the timer doesn't go up anymore but the live stream it self is still running. At first I thought it was due to lag as whenever the stream lags that issue would arise so I played around with the lag timer but have found no solution. However sometimes the recording goes well without any issue but often than not the "freezing" would occur, tested on multiple and people and streams. Any help would be appreciated.

**Comment by Sullyscharger** [comment]
I thought that too so I moved to an Ethernet connection but it still happens

**Comment by danrynr** [comment]
how many minutes have passed until it stalled?

**Comment by Sullyscharger** [comment]
Around 2-5 mins

**Comment by Sullyscharger** [comment]
Update: changing ports and cable worked for a day but now it's gone back to stalling again, I've checked my network connection and it has been consistently high so I don't think it's my internet. Any input would be appreciated

**Comment by roju** [comment]
I was able to reproduce this by disabling my network connection while recording. Should be fixed in v4.2, but let me know if it's still happening.

**Comment by Sullyscharger** [comment]
Thanks for the update! Will do
