### ISSUE TITLE
ERROR - Recording error: local variable 'stats_shown' referenced before assignment

### ISSUE THREAD

**Issue by potatomilk23** [roju/tiktok-live-recorder#5]
I keep getting this error. How can I fix this?
![image](https://github.com/roju/tiktok-live-recorder/assets/108025138/61189b93-5ebf-4e2a-81d8-0ea2eb018c3f)

**Comment by roju** [comment]
I haven't seen this error before. However it looks like you're on Windows, and I haven't tested the script on Windows yet. It's on the TODO list.

If you find a solution for this or any other Windows-related issues, a pull request would be much appreciated.

**Comment by Geczy** [comment]
i was running into this error too, very easily reproducible if you just clone my #7 branch and try to run it. opened #6 which fixes it

**Comment by roju** [comment]
should be fixed by 56988bc
