### ISSUE TITLE
Tor Proxy

### ISSUE THREAD

**Issue by guitiba05** [roju/tiktok-live-recorder#9]
Does TOR browser has to be running in order to the proxy system to work?
Edit: Im constantly getting a proxy error:
`2023-09-12 19:47:50,973 - ERROR - SOCKSHTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: /@yasmin_iunes/live (Caused by NewConnectionError('<urllib3. contrib.socks.SOCKSHTTPSConnection object at 0x000001AA4FF13910>: Failed to establish a new connection: [WinError 10061] No connections could be made because the target machine actively refused them'))`

**Comment by roju** [comment]
In my case, I installed it on Ubuntu with `apt install tor` which also installs and enables torsocks proxy. Never opened the TOR browser.
